blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/Rollandcodes/schedule-app/discussions
    about: Need help self-hosting or have a general question about Schedule? Open a discussion
